// <auto-generated />
using System;
using CliverSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliverSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220719051916_AddTitlePost")]
    partial class AddTitlePost
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CliverSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Graphics & Design"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Writing & Translation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Video & Animation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Music & Audio"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Programming & Tech"
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("CanContentUpload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDesignCustomized")
                        .HasColumnType("bit");

                    b.Property<int>("DeliveryTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSourceCode")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponsiveDesign")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfRevisions")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("CliverSystem.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BasicPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasOfferPackages")
                        .HasColumnType("bit");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PremiumPackageId")
                        .HasColumnType("int");

                    b.Property<int?>("StandardPackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicPackageId");

                    b.HasIndex("PremiumPackageId");

                    b.HasIndex("StandardPackageId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CliverSystem.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Brand Style Guides"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Game Art"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Illustration"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "NFT Art"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Portraits & Caricatures"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Pattern Design"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Cartoons & Comics"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Name = "WordPress"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Name = "Website Builders & CMS"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Name = "Development for Streamers"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Name = "Web Programming"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Name = "E - Commerce Development"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Name = "Mobile Apps"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Name = "Desktop Applications"
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("AvailableForWithdrawal")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExpectedEarnings")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NetIncome")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PendingClearance")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsedForPurchases")
                        .HasColumnType("bigint");

                    b.Property<long>("Withdrawn")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CliverSystem.Models.Post", b =>
                {
                    b.HasOne("CliverSystem.Models.Package", "BasicPackage")
                        .WithMany()
                        .HasForeignKey("BasicPackageId");

                    b.HasOne("CliverSystem.Models.Package", "PremiumPackage")
                        .WithMany()
                        .HasForeignKey("PremiumPackageId");

                    b.HasOne("CliverSystem.Models.Package", "StandardPackage")
                        .WithMany()
                        .HasForeignKey("StandardPackageId");

                    b.HasOne("CliverSystem.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicPackage");

                    b.Navigation("PremiumPackage");

                    b.Navigation("StandardPackage");

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.Subcategory", b =>
                {
                    b.HasOne("CliverSystem.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CliverSystem.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("CliverSystem.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
