// <auto-generated />
using System;
using CliverSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliverSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230311030051_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CliverSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Graphics & Design"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Writing & Translation"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Video & Animation"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Music & Audio"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Programming & Tech"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Trending"
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomPackageId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("RepliedToMessageId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomPackageId");

                    b.HasIndex("PostId");

                    b.HasIndex("RepliedToMessageId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("CliverSystem.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueBy")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeftRevisionTimes")
                        .HasColumnType("int");

                    b.Property<long>("LockedMoney")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("RevisionTimes")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("PackageId");

                    b.HasIndex("SellerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CliverSystem.Models.OrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ResourceId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("CliverSystem.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpirationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfRevisions")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(12)")
                        .HasDefaultValue("Basic");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("Type");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("CliverSystem.Models.Parameters", b =>
                {
                    b.Property<int>("NumDaysReturnMoney")
                        .HasColumnType("int");

                    b.HasKey("NumDaysReturnMoney");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            NumDaysReturnMoney = 5
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasOfferPackages")
                        .HasColumnType("bit");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingAvg")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("Title");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CliverSystem.Models.RecentPost", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("RecentPost");
                });

            modelBuilder.Entity("CliverSystem.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("CliverSystem.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("CliverSystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("LastMessageId")
                        .HasColumnType("int");

                    b.Property<string>("MemberKeys")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MemberKeys")
                        .IsUnique();

                    b.ToTable("Room");
                });

            modelBuilder.Entity("CliverSystem.Models.RoomMember", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomId");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("MemberId");

                    b.HasKey("RoomId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("RoomMembers");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedLists");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedSeller", b =>
                {
                    b.Property<int>("SavedListId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SavedListId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedSellers");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedService", b =>
                {
                    b.Property<int>("SavedListId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SavedListId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("SavedServices");
                });

            modelBuilder.Entity("CliverSystem.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long?>("Budget")
                        .HasColumnType("bigint");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceRequest");
                });

            modelBuilder.Entity("CliverSystem.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Social Media Advertising"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Search Engine Optimization (SEO)"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Local SEO"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Marketing Strategy"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Public Relations"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Guest Posting"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Video Marketing"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Web Analytics"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Text Message Marketing"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Crowdfunding"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Marketing Advice"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Search Engine Marketing (SEM)"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Display Advertising"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "E-Commerce Marketing"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Influencer Marketing"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Community Management"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Mobile App Marketing"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Music Promotion"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Book & eBook Marketing"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Podcast Marketing"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Affiliate Marketing"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Icon = "https://picsum.photos/50",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Brand Style Guides"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Fonts & TypographyNEW"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Business Cards & Stationery"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Game Art"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Graphics for Streamers"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Twitch Store"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Illustration"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "NFT Art"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Pattern Design"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Portraits & Caricatures"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Cartoons & Comics"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Tattoo Design"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Storyboards"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Website Design"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "App Design"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "UX Design"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Landing Page Design"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Icon Design"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Social Media Design"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Email Design"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Web Banners"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Signage Design"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Packaging & Covers"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Packaging & Label Design"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Book Design"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Album Cover Design"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Podcast Cover Art"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Icon = "https://picsum.photos/50",
                            Name = "Car Wraps"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Articles & Blog Posts"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Proofreading & Editing"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Resume Writing"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Cover Letters"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "LinkedIn Profiles"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Ad Copy"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Sales Copy"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Social Media Copy"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Email Copy"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Case Studies"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Book & eBook Writing"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Book Editing"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Scriptwriting"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Podcast Writing"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Beta Reading"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Creative Writing"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Brand Voice & Tone"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "UX Writing"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Speechwriting"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "eLearning Content Development"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            Icon = "https://picsum.photos/50",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Short Video Ads"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Whiteboard & Animated Explainers"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Character Animation"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Lyric & Music Videos"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Logo Animation"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Intros & Outros"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Visual Effects"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Subtitles & Captions"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Spokesperson Videos"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Unboxing Videos"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 4,
                            Icon = "https://picsum.photos/50",
                            Name = "Animated GIFs"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Voice Over"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Producers & Composers"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Singers & Vocalists"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Mixing & Mastering"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Session Musicians"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Online Music Lessons"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Podcast Editing"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Songwriters"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Beat Making"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Audiobook Production"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Audio Ads Production"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 5,
                            Icon = "https://picsum.photos/50",
                            Name = "Sound Design"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "WordPress"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Website Builders & CMS"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Development for Streamers"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Web Programming"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "E-Commerce Development"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Mobile Apps"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Desktop Applications"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Chatbots"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Support & IT"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Online Coding Lessons"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Cybersecurity & Data Protection"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Electronics Engineering"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Convert Files"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "User Testing"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "QA & Review"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Blockchain & Cryptocurrency"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "NFT Development"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Databases"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Processing"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Engineering"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 6,
                            Icon = "https://picsum.photos/50",
                            Name = ""
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Virtual Assistant"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "E-Commerce Management"
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Market Research"
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Customer Care"
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "CRM Management NEW"
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "ERP ManagementNEW"
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Supply Chain Management"
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Event ManagementNEW"
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Game Concept Design"
                        },
                        new
                        {
                            Id = 135,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Business Plans"
                        },
                        new
                        {
                            Id = 136,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Financial Consulting"
                        },
                        new
                        {
                            Id = 137,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Legal Consulting"
                        },
                        new
                        {
                            Id = 138,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Business Consulting"
                        },
                        new
                        {
                            Id = 139,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Presentations"
                        },
                        new
                        {
                            Id = 140,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "HR Consulting"
                        },
                        new
                        {
                            Id = 141,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Career Counseling"
                        },
                        new
                        {
                            Id = 142,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Entry"
                        },
                        new
                        {
                            Id = 143,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Analytics"
                        },
                        new
                        {
                            Id = 144,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Data Visualization"
                        },
                        new
                        {
                            Id = 145,
                            CategoryId = 7,
                            Icon = "https://picsum.photos/50",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 146,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Online Tutoring"
                        },
                        new
                        {
                            Id = 147,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 148,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Astrology & Psychics"
                        },
                        new
                        {
                            Id = 149,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Modeling & Acting"
                        },
                        new
                        {
                            Id = 150,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Wellness"
                        },
                        new
                        {
                            Id = 151,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Traveling"
                        },
                        new
                        {
                            Id = 152,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Fitness Lessons"
                        },
                        new
                        {
                            Id = 153,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Dance Lessons"
                        },
                        new
                        {
                            Id = 154,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Life Coaching"
                        },
                        new
                        {
                            Id = 155,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Greeting Cards & Videos"
                        },
                        new
                        {
                            Id = 156,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Personal Stylists"
                        },
                        new
                        {
                            Id = 157,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Cooking Lessons"
                        },
                        new
                        {
                            Id = 158,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Craft Lessons"
                        },
                        new
                        {
                            Id = 159,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Arts & Crafts"
                        },
                        new
                        {
                            Id = 160,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Family & Genealogy"
                        },
                        new
                        {
                            Id = 161,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Collectibles"
                        },
                        new
                        {
                            Id = 162,
                            CategoryId = 8,
                            Icon = "https://picsum.photos/50",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 163,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Dropshipping"
                        },
                        new
                        {
                            Id = 164,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "E-Commerce Marketing"
                        },
                        new
                        {
                            Id = 165,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 166,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Discord Services"
                        },
                        new
                        {
                            Id = 167,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "NFT Services"
                        },
                        new
                        {
                            Id = 168,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Architecture & Interior Design"
                        },
                        new
                        {
                            Id = 169,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Data"
                        },
                        new
                        {
                            Id = 170,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Resume Writing"
                        },
                        new
                        {
                            Id = 171,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Search Engine Optimization (SEO)"
                        },
                        new
                        {
                            Id = 172,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Character Modeling"
                        },
                        new
                        {
                            Id = 173,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Character Animation"
                        },
                        new
                        {
                            Id = 174,
                            CategoryId = 9,
                            Icon = "https://picsum.photos/50",
                            Name = "Image Editing"
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.TransactionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("WalletId");

                    b.ToTable("TransactionHistory");
                });

            modelBuilder.Entity("CliverSystem.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://t4.ftcdn.net/jpg/02/23/50/73/360_F_223507349_F5RFU3kL6eMt5LijOaMbWLeHUTv165CB.jpg");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingAvg")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "53f891d8-bd32-40cf-a30c-04f2d5ecf164",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "test@gmail.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "Test 1",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 1
                        },
                        new
                        {
                            Id = "3dbb7902-74a5-4113-9052-a13919a73949",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "test2@gmail.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "Test 2",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 2
                        },
                        new
                        {
                            Id = "f5a6e9d2-a322-4e0d-bf39-8acf7b6b2fc6",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "test3@gmail.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "Test 3",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 3
                        },
                        new
                        {
                            Id = "fedb88e2-decb-45a2-a0f1-8edc92b0b918",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "admin@admin.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "admin",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 4
                        },
                        new
                        {
                            Id = "733a44cc-f3b5-4e79-8dda-afb6be9c72a3",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "test4@gmail.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "test 4",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 9
                        },
                        new
                        {
                            Id = "19328465-fcf8-4315-b687-bba6b86d13ed",
                            Avatar = "https://picsum.photos/200",
                            CreatedAt = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Email = "test5@gmail.com",
                            IsActive = false,
                            IsVerified = true,
                            Languages = "",
                            Name = "test 5",
                            Password = "123123123",
                            RatingAvg = 0.0,
                            RatingCount = 0,
                            Skills = "",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WalletId = 10
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("AvailableForWithdrawal")
                        .HasColumnType("bigint");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpectedEarnings")
                        .HasColumnType("bigint");

                    b.Property<long>("NetIncome")
                        .HasColumnType("bigint");

                    b.Property<long>("PendingClearance")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedForPurchases")
                        .HasColumnType("bigint");

                    b.Property<long>("Withdrawn")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Wallet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        },
                        new
                        {
                            Id = 2,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        },
                        new
                        {
                            Id = 3,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        },
                        new
                        {
                            Id = 4,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        },
                        new
                        {
                            Id = 9,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        },
                        new
                        {
                            Id = 10,
                            AvailableForWithdrawal = 0L,
                            Balance = 0L,
                            ExpectedEarnings = 0L,
                            NetIncome = 0L,
                            PendingClearance = 0L,
                            UsedForPurchases = 0L,
                            Withdrawn = 0L
                        });
                });

            modelBuilder.Entity("CliverSystem.Models.Message", b =>
                {
                    b.HasOne("CliverSystem.Models.Package", "CustomPackage")
                        .WithMany()
                        .HasForeignKey("CustomPackageId");

                    b.HasOne("CliverSystem.Models.Post", "RelatedPost")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("CliverSystem.Models.Message", "RepliedToMessage")
                        .WithMany()
                        .HasForeignKey("RepliedToMessageId");

                    b.HasOne("CliverSystem.Models.Room", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomPackage");

                    b.Navigation("RelatedPost");

                    b.Navigation("RepliedToMessage");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CliverSystem.Models.Order", b =>
                {
                    b.HasOne("CliverSystem.Models.User", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.Package", "Package")
                        .WithMany("Orders")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Package");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CliverSystem.Models.OrderHistory", b =>
                {
                    b.HasOne("CliverSystem.Models.Order", "Order")
                        .WithMany("Histories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Order");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CliverSystem.Models.Package", b =>
                {
                    b.HasOne("CliverSystem.Models.Post", "Post")
                        .WithMany("Packages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CliverSystem.Models.Post", b =>
                {
                    b.HasOne("CliverSystem.Models.Subcategory", "Subcategory")
                        .WithMany("Posts")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.RecentPost", b =>
                {
                    b.HasOne("CliverSystem.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.Review", b =>
                {
                    b.HasOne("CliverSystem.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.RoomMember", b =>
                {
                    b.HasOne("CliverSystem.Models.User", "Member")
                        .WithMany("RoomMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.Room", "Room")
                        .WithMany("RoomMembers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedList", b =>
                {
                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedSeller", b =>
                {
                    b.HasOne("CliverSystem.Models.SavedList", "SavedList")
                        .WithMany("SavedSellers")
                        .HasForeignKey("SavedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedService", b =>
                {
                    b.HasOne("CliverSystem.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.SavedList", "SavedList")
                        .WithMany("SavedServices")
                        .HasForeignKey("SavedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("SavedList");
                });

            modelBuilder.Entity("CliverSystem.Models.ServiceRequest", b =>
                {
                    b.HasOne("CliverSystem.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliverSystem.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId");

                    b.HasOne("CliverSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CliverSystem.Models.Subcategory", b =>
                {
                    b.HasOne("CliverSystem.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CliverSystem.Models.TransactionHistory", b =>
                {
                    b.HasOne("CliverSystem.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("CliverSystem.Models.Wallet", "Wallet")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CliverSystem.Models.User", b =>
                {
                    b.HasOne("CliverSystem.Models.Wallet", "Wallet")
                        .WithOne("User")
                        .HasForeignKey("CliverSystem.Models.User", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CliverSystem.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("CliverSystem.Models.Order", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CliverSystem.Models.Package", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CliverSystem.Models.Post", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("CliverSystem.Models.Room", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("RoomMembers");
                });

            modelBuilder.Entity("CliverSystem.Models.SavedList", b =>
                {
                    b.Navigation("SavedSellers");

                    b.Navigation("SavedServices");
                });

            modelBuilder.Entity("CliverSystem.Models.Subcategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CliverSystem.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Posts");

                    b.Navigation("RoomMembers");
                });

            modelBuilder.Entity("CliverSystem.Models.Wallet", b =>
                {
                    b.Navigation("TransactionHistories");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
